### ISSUE TITLE
Clear the label after filling

### ISSUE THREAD

**Issue by lpemeg** [mdikcinar/searchable_dropdown#1]
Your project was perfect, I really liked it and I'm using it in my application, but I have a problem that I already solved by changing your project in my application that I wanted to pass on so you could change it too, when we select the label it is filled in showing our selection, but if I want to clean it, I can't because I would need to clean the selection label. Could you solve this in your project? Thanks in advance for your project.

**Comment by mdikcinar** [comment]
Hi, thanks for your good wish and feedback. I will be pleased if you send your changes as a pull request.

**Comment by mdikcinar** [comment]
https://github.com/mdikcinar/searchable_dropdown/pull/4
