### ISSUE TITLE
Dropdown popup spacing issue

### ISSUE THREAD

**Issue by varindergroove** [mdikcinar/searchable_dropdown#12]
Search dropdown field widget and dropdown popup widget between spacing issue. not follow the dropdown field. I use the SearchableDropdown paginated widget. I attach the files. you see it, i click the Business Group field and show dropdown popup show very down of the field . please fix this asap

![Capture](https://github.com/mdikcinar/searchable_dropdown/assets/74890964/00e10ff8-b055-4edb-ac62-53d76168643b)

**Comment by mdikcinar** [comment]
Hi, Could you share an example code snippet so that i can take a look?

**Comment by varindergroove** [comment]
Container(
              child: SearchableDropdownFormField<String>.paginated(
                hintText: Text(value),
                trailingClearIcon: SizedBox.shrink(),
                paginatedRequest: (page, search) async {
                  

                  final List<String> paginatedList =
                      await _formNotifier.fetchAutoCompleteApi(
                      offset: page-1,
                      );

                  return paginatedList
                      .map((e) => SearchableDropdownMenuItem(
                      value: e,
                      label: e,
                      child:
                      Text(e, style: TextStyle(fontSize: 14))))
                      .toList();
                },
                onChanged: (value) async {
                  if (value != null) {
                    
                  }
                },
                changeCompletionDelay: Duration(milliseconds: 600),
                  backgroundDecoration: (child) {
                    return InputDecorator(
                      decoration: InputDecoration(
                        contentPadding: EdgeInsets.only(left: 10, right: 10, top: 7, bottom: 7),
                        border: OutlineInputBorder(
                            borderSide: BorderSide(
                                color: changeStringToColor(widget.activeColor))),
                        enabledBorder: OutlineInputBorder(
                            borderSide: BorderSide(
                                color: changeStringToColor(widget.unActiveColor))),
                        focusedBorder: OutlineInputBorder(
                            borderSide: BorderSide(
                                color: changeStringToColor(widget.activeColor))),
                        errorBorder: OutlineInputBorder(
                            borderSide: BorderSide(
                                color: changeStringToColor(widget.activeColor))),
                        focusedErrorBorder: OutlineInputBorder(
                            borderSide: BorderSide(
                                color: changeStringToColor(widget.activeColor))),
                        focusColor: changeStringToColor(widget.activeColor),
                        //helperText: _info,
                        helperMaxLines: 1,
                        helperStyle: TextStyle(
                            color: changeStringToColor("TM_COLOR_8"),
                            fontStyle: FontStyle.italic),
                        hintStyle: TextStyle(
                            color: changeStringToColor(widget.unActiveColor)),
                        labelStyle: TextStyle(
                            color: changeStringToColor(widget.unActiveColor)),
                        labelText: widget.structure.isRequired
                            ? "${widget.structure.labelName!}*"
                            : widget.structure.labelName,
                        prefixIconColor: changeStringToColor(widget.activeColor),
                        prefixIcon: widget.structure.icon != null
                            ? KeyIconWidget(
                          iconKey: widget.structure.icon,
                          hexColor: _focusNode.hasFocus
                              ? widget.activeColor
                              : widget.unActiveColor,
                        )
                            : null,
                        suffixIconColor: changeStringToColor(widget.activeColor),
                        suffixIcon: widget.structure.isUnique
                            ? KeyIconWidget(
                          iconKey: "auto_awesome",
                          hexColor: _focusNode.hasFocus
                              ? widget.activeColor
                              : widget.unActiveColor,
                        )
                            : null,
                        floatingLabelAlignment: FloatingLabelAlignment.start,
                        floatingLabelStyle: MaterialStateTextStyle.resolveWith(
                                (Set<MaterialState> states) {
                              final Color color = changeStringToColor(widget.activeColor);
                              return TextStyle(color: color, letterSpacing: 1.3);
                            }),
                        //errorText: _errorText,
                        errorStyle: TextStyle(color: Colors.red),
                      ),
                      child: child,
                    );
                  }
              ),
            )

**Comment by mdikcinar** [comment]
I couldn't see any problems. I guess someting else is triggering this issue on your code.
![Simulator Screen Shot - iPhone 14 Pro - 2023-06-12 at 18 08 31](https://github.com/mdikcinar/searchable_dropdown/assets/77580742/1d7abe11-1e06-44a9-ba58-bad46d2bfa3c)

**Comment by varindergroove** [comment]
if change the height of InputDocorator then see this issue, i have use two different way but same problem occur.
![Screenshot_1686632773](https://github.com/mdikcinar/searchable_dropdown/assets/74890964/2ae83102-d89b-470a-9c63-08517d9036fb)

**Comment by varindergroove** [comment]
are you there?

**Comment by wendellavila** [comment]
I can confirm this issue exists. It appears to be caused by line 383 in [lib/src/searchable_dropdown.dart](https://github.com/mdikcinar/searchable_dropdown/blob/main/lib/src/searchable_dropdown.dart):
`const dialogOffset = 35; //Dialog offset from dropdown`

Setting it to zero fixed the spacing for me. This should be customizable instead of a constant value.

**Comment by mdikcinar** [comment]
i added dialogOffset value to the constructor. Now its constomizable.
https://github.com/mdikcinar/searchable_dropdown/tree/feature/1.3.0
