### ISSUE TITLE
Option to clear label programmatically also

### ISSUE THREAD

**Issue by networlddeveloper** [mdikcinar/searchable_dropdown#16]
Hello, hope you are doing good, I already mentioned this thing can you please look at it ?

In simple textfield we have the option to clear its value when we use it like this _controller.text = "" , i cannot find that for this drop down, like i have many fields including this drop down, and what I need is when the user finish a process then the value should be automatically(programmatically) cleared, not by pressing the cross button , you got my point?

**Comment by mdikcinar** [comment]
Hi thanks for feedback, i refactored the code a bit.  Now you can create your controller and manupulate the value via controller.

https://github.com/mdikcinar/searchable_dropdown/tree/feature/1.3.0

**Comment by networlddeveloper** [comment]
Thank you so much, I will update in the code

**Comment by networlddeveloper** [comment]
Hello, hope you are doing well, can you please upload that changes on the pub.dev, So I can implement it in the project, thanks
