### ISSUE TITLE
initialvalue not working

### ISSUE THREAD

**Issue by eng-sayed** [mdikcinar/searchable_dropdown#17]
initialvalue not working when i trying to give the dropdown a inital data to show
![Screenshot 2023-12-17 at 1 14 17 AM](https://github.com/mdikcinar/searchable_dropdown/assets/56679747/11e3f20f-00ff-4458-90ab-94f2994e9a8b)

**Comment by mdikcinar** [comment]
Hi, thanks for the feedback, its fixed now.
https://github.com/mdikcinar/searchable_dropdown/tree/feature/1.3.0
