### ISSUE TITLE
Duplicate page requests

### ISSUE THREAD

**Issue by Gantushig77** [mdikcinar/searchable_dropdown#20]
The "paginatedRequest" function triggers 3 times in a row on the second page resulting duplicate rows.

**Comment by mdikcinar** [comment]
Hi have you tried with the latest commit id? I did some changes and improved that feature but i couldn’t publish it yet. If it still exist on last commit i will check again.

**Comment by mdikcinar** [comment]
https://pub.dev/packages/searchable_paginated_dropdown
v1.3.0 is live on pub dev.
