### ISSUE TITLE
pagination search issue

### ISSUE THREAD

**Issue by varindergroove** [mdikcinar/searchable_dropdown#6]
Please add _debounce feature in pagination , because some time result show duplicate. please asap resolve this issue

**Comment by mdikcinar** [comment]
https://github.com/mdikcinar/searchable_dropdown/pull/7

**Comment by varindergroove** [comment]
not perfectly work debounce

I want to ,If I type in search field after complete my typing then hit the remote api otherwise continue the typing

**Comment by mdikcinar** [comment]
there is already 800ms debonce for that case. Is it not working? can you share an example case.

**Comment by varindergroove** [comment]
i thinks its work only 200ms,

If you can change the functionality of debonce like this


Timer? _debounce;
_onSearchChanged(String query) {
    if (_debounce?.isActive ?? false) _debounce.cancel();
    _debounce = Timer(const Duration(milliseconds: 500), () {
        // do something with query
    });
    }
    
    if typing continue the priovous cancel debounce and create new one 

now work is handle for 800ms the hit api if i typing is continue or not that why hit api twice and result show twice.

please use this code for dobouce or if possible to set the timing of dobouce in paginated function

**Comment by mdikcinar** [comment]
Yeah but i already have a cancelable operation for search bar's on change, but i will also test it when i available. 
```dart
    CancelableOperation<dynamic>? cancelableOperation;

    void startCancelableOperation() {
      cancelableOperation = CancelableOperation.fromFuture(
        Future.delayed(changeCompletionDelay),
      );
    }

    return Padding(
      padding: const EdgeInsets.all(8),
      child: TextField(
        controller: controller,
        focusNode: focusNode,
        onChanged: (value) async {
          await cancelableOperation?.cancel();
          startCancelableOperation();
          await cancelableOperation?.value.whenComplete(() {
            onChangeComplete?.call(value);
          });
        },
        style: style,
        decoration: InputDecoration(
          contentPadding: EdgeInsets.zero,
          isDense: true,
          border: InputBorder.none,
          hintText: hintText,
          icon: leadingIcon,
        ),
      ),
    );
```

**Comment by varindergroove** [comment]
if you are think code is ok then please check it dropdown value not show duplicate many times. please show unique entry. otherwise please implement this dobounce method.

**Comment by mdikcinar** [comment]
I have tested my code, it works well. But i figure out that the completion delay is default 200ms. So i added that value to constructor. Now you can give your completion delay as what you want. Can you try it on https://github.com/mdikcinar/searchable_dropdown/tree/feature/searchDelay branch. You sould see changeCompletionDelay parametter.

pubspec.yaml example for branch
```
 searchable_paginated_dropdown:
    git:
      url: git@github.com:mdikcinar/searchable_dropdown.git
      ref: feature/searchDelay
```

**Comment by mdikcinar** [comment]
If you say thats okey, i will publish a new version. But if your problem still continues i need an example case for that bug. Its not happening on my example project.

**Comment by varindergroove** [comment]
now your example code is working fine please push the code i will test it on our code

**Comment by mdikcinar** [comment]
https://github.com/mdikcinar/searchable_dropdown/pull/9
